# Generated by Django 4.2.7 on 2025-10-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suntech_device_id', models.IntegerField(help_text='ID do dispositivo na plataforma Suntech', unique=True, verbose_name='ID Dispositivo Suntech')),
                ('suntech_vehicle_id', models.IntegerField(help_text='ID do veículo na plataforma Suntech', verbose_name='ID Veículo Suntech')),
                ('imei', models.CharField(blank=True, help_text='IMEI do dispositivo', max_length=20, null=True, verbose_name='IMEI')),
                ('label', models.CharField(blank=True, help_text='Nome/identificação do dispositivo na Suntech', max_length=100, null=True, verbose_name='Identificação')),
                ('last_position_date', models.DateTimeField(blank=True, help_text='Data/hora da última posição GPS', null=True, verbose_name='Data Última Posição')),
                ('last_system_date', models.DateTimeField(blank=True, help_text='Data/hora de recebimento no servidor Suntech', null=True, verbose_name='Data Última Atualização Sistema')),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Última Latitude')),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Última Longitude')),
                ('last_address', models.TextField(blank=True, null=True, verbose_name='Último Endereço')),
                ('last_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Última Velocidade (km/h)')),
                ('last_ignition_status', models.CharField(blank=True, choices=[('ON', 'Ligada'), ('OFF', 'Desligada')], max_length=10, null=True, verbose_name='Status Ignição')),
                ('odometer', models.BigIntegerField(blank=True, null=True, verbose_name='Odômetro (metros)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['suntech_device_id'], name='devices_dev_suntech_8fb5d4_idx'), models.Index(fields=['vehicle'], name='devices_dev_vehicle_262ce9_idx'), models.Index(fields=['is_active'], name='devices_dev_is_acti_52b321_idx')],
            },
        ),
    ]
