# Generated by Django 4.2.7 on 2025-10-08 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo da rota (ex: São Paulo - Rio de Janeiro)', max_length=200, verbose_name='Nome da Rota')),
                ('description', models.TextField(blank=True, help_text='Detalhes adicionais sobre a rota', null=True, verbose_name='Descrição')),
                ('origin_name', models.CharField(help_text='Nome do local de origem', max_length=200, verbose_name='Nome Origem')),
                ('origin_address', models.TextField(help_text='Endereço completo do ponto de origem', verbose_name='Endereço Origem')),
                ('origin_latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude Origem')),
                ('origin_longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude Origem')),
                ('destination_name', models.CharField(help_text='Nome do local de destino', max_length=200, verbose_name='Nome Destino')),
                ('destination_address', models.TextField(help_text='Endereço completo do ponto de destino', verbose_name='Endereço Destino')),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude Destino')),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude Destino')),
                ('distance_meters', models.IntegerField(blank=True, help_text='Distância calculada pelo OpenStreetMap', null=True, verbose_name='Distância (metros)')),
                ('estimated_duration_seconds', models.IntegerField(blank=True, help_text='Tempo estimado de viagem calculado pelo OpenStreetMap', null=True, verbose_name='Duração Estimada (segundos)')),
                ('route_geometry', models.JSONField(blank=True, help_text='Coordenadas da rota em formato GeoJSON', null=True, verbose_name='Geometria da Rota')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('last_calculated_at', models.DateTimeField(blank=True, help_text='Data do último cálculo da rota', null=True, verbose_name='Última Calculo')),
                ('transportadora', models.ForeignKey(limit_choices_to={'user_type': 'TRANSPORTADORA'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Transportadora')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transportadora', 'is_active'], name='routes_rout_transpo_2db806_idx'), models.Index(fields=['name'], name='routes_rout_name_812281_idx')],
            },
        ),
    ]
