# Generated by Django 4.2.7 on 2025-10-07 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_VIAGEM', 'Em Viagem'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=20, verbose_name='Status')),
                ('placa', models.CharField(help_text='Formato: ABC1234 ou ABC1D23 (Mercosul)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Placa deve estar no formato ABC1234 ou ABC1D23 (Mercosul)', regex='^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$')], verbose_name='Placa')),
                ('ano', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Ano deve conter 4 dígitos', regex='^\\d{4}$')], verbose_name='Ano')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('renavam', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Renavam deve conter exatamente 11 dígitos', regex='^\\d{11}$')], verbose_name='Renavam')),
                ('chassi', models.CharField(help_text='17 caracteres alfanuméricos (VIN)', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Chassi deve conter 17 caracteres alfanuméricos (sem I, O, Q)', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='Chassi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('transportadora', models.ForeignKey(limit_choices_to={'user_type': 'TRANSPORTADORA'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Transportadora')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['placa'], name='vehicles_ve_placa_6c3f1f_idx'), models.Index(fields=['transportadora', 'status'], name='vehicles_ve_transpo_21aea4_idx')],
            },
        ),
    ]
