# Generated by Django 4.2.7 on 2025-10-08 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Código único do SM (ex: SM-2024-0001)', max_length=100, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(help_text='Nome descritivo do monitoramento', max_length=200, verbose_name='Nome do Monitoramento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('planned_start_date', models.DateTimeField(help_text='Data/hora planejada para início da viagem', verbose_name='Data Planejada de Início')),
                ('planned_end_date', models.DateTimeField(help_text='Data/hora planejada para término da viagem', verbose_name='Data Planejada de Término')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Real de Início')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Real de Término')),
                ('device_validated_at', models.DateTimeField(help_text='Data/hora da validação do rastreador', verbose_name='Dispositivo Validado em')),
                ('device_was_updated', models.BooleanField(default=False, help_text='Indica se o dispositivo estava atualizado no momento da criação', verbose_name='Dispositivo Estava Atualizado')),
                ('cargo_description', models.TextField(blank=True, null=True, verbose_name='Descrição da Carga')),
                ('cargo_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Carga')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monitoring_systems', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_systems', to='drivers.driver', verbose_name='Motorista')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_systems', to='routes.route', verbose_name='Rota')),
                ('transportadora', models.ForeignKey(limit_choices_to={'user_type': 'TRANSPORTADORA'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_systems', to=settings.AUTH_USER_MODEL, verbose_name='Transportadora')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_systems', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Sistema de Monitoramento',
                'verbose_name_plural': 'Sistemas de Monitoramento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transportadora', 'status'], name='monitoring__transpo_0e6bcc_idx'), models.Index(fields=['identifier'], name='monitoring__identif_c9f9d7_idx'), models.Index(fields=['status', 'is_active'], name='monitoring__status_50b790_idx')],
            },
        ),
    ]
