# Generated by Django 4.2.7 on 2025-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsystem',
            name='device_validated_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora da validação do rastreador (preenchido automaticamente)', null=True, verbose_name='Dispositivo Validado em'),
        ),
    ]
