# Generated by Django 4.2.7 on 2025-10-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_monitoringsystem_device_validated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude da posição', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude da posição', max_digits=10, verbose_name='Longitude')),
                ('address', models.CharField(blank=True, help_text='Endereço aproximado da posição', max_length=500, null=True, verbose_name='Endereço')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidade (km/h)')),
                ('heading', models.IntegerField(blank=True, help_text='Direção do veículo em graus (0-360)', null=True, verbose_name='Direção (graus)')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Altitude (m)')),
                ('device_timestamp', models.DateTimeField(help_text='Data/hora reportada pelo rastreador', verbose_name='Data/Hora do Dispositivo')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que a posição foi registrada no sistema', verbose_name='Data/Hora do Servidor')),
                ('extra_data', models.JSONField(blank=True, help_text='Dados adicionais da API (ignição, bateria, etc.)', null=True, verbose_name='Dados Extras')),
                ('monitoring_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='monitoring.monitoringsystem', verbose_name='Sistema de Monitoramento')),
            ],
            options={
                'verbose_name': 'Histórico de Posição',
                'verbose_name_plural': 'Histórico de Posições',
                'ordering': ['-device_timestamp'],
                'indexes': [models.Index(fields=['monitoring_system', '-device_timestamp'], name='monitoring__monitor_c573eb_idx'), models.Index(fields=['monitoring_system', 'server_timestamp'], name='monitoring__monitor_accccb_idx')],
                'unique_together': {('monitoring_system', 'device_timestamp', 'latitude', 'longitude')},
            },
        ),
    ]
