# Generated by Django 4.2.7 on 2025-10-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_vehiclepositionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsystem',
            name='alerts_data',
            field=models.JSONField(blank=True, default=list, help_text='Histórico de alertas gerados durante a viagem', verbose_name='Dados de Alertas'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='average_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidade Média (km/h)'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='has_active_deviation',
            field=models.BooleanField(default=False, help_text='Indica se o veículo está atualmente fora da rota', verbose_name='Desvio Ativo'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='last_deviation_detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Desvio Detectado em'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='max_speed_recorded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidade Máxima Registrada (km/h)'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='route_deviation_tolerance_meters',
            field=models.IntegerField(default=500, help_text='Distância máxima permitida da rota planejada antes de alertar (em metros)', verbose_name='Tolerância Desvio de Rota (m)'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='total_distance_traveled',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distância total calculada a partir das posições capturadas', max_digits=10, verbose_name='Distância Total Percorrida (km)'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='total_route_deviations',
            field=models.IntegerField(default=0, help_text='Número de vezes que o veículo saiu da rota planejada', verbose_name='Total de Desvios de Rota'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='total_stops',
            field=models.IntegerField(default=0, help_text='Número de paradas detectadas (velocidade = 0 por mais de 5 min)', verbose_name='Total de Paradas'),
        ),
    ]
