# Generated by Django 4.2.7 on 2025-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_add_trip_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsystem',
            name='is_currently_stopped',
            field=models.BooleanField(default=False, help_text='Indica se o veículo está parado no momento (velocidade = 0)', verbose_name='Veículo Parado Atualmente'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='last_stop_alert_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do último alerta de parada prolongada', null=True, verbose_name='Último Alerta de Parada em'),
        ),
        migrations.AddField(
            model_name='monitoringsystem',
            name='stopped_since',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o veículo parou (velocidade chegou a 0)', null=True, verbose_name='Parado Desde'),
        ),
        migrations.AlterField(
            model_name='monitoringsystem',
            name='route_deviation_tolerance_meters',
            field=models.IntegerField(default=200, help_text='Distância máxima permitida da rota planejada antes de alertar (em metros)', verbose_name='Tolerância Desvio de Rota (m)'),
        ),
    ]
