# Generated by Django 4.2.7 on 2025-10-07 20:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do motorista', max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='CPF no formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('rg', models.CharField(help_text='RG no formato: 00.000.000-0', max_length=12, validators=[django.core.validators.RegexValidator(message='RG deve estar no formato: 00.000.000-0', regex='^\\d{2}\\.\\d{3}\\.\\d{3}-\\d{1}$')], verbose_name='RG')),
                ('cnh', models.CharField(help_text='Carteira Nacional de Habilitação (11 dígitos)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CNH deve conter 11 dígitos', regex='^\\d{11}$')], verbose_name='CNH')),
                ('nome_do_pai', models.CharField(blank=True, help_text='Nome completo do pai', max_length=255, verbose_name='Nome do Pai')),
                ('nome_da_mae', models.CharField(help_text='Nome completo da mãe', max_length=255, verbose_name='Nome da Mãe')),
                ('tipo_de_veiculo', models.CharField(help_text='Tipo de veículo que o motorista está habilitado a dirigir', max_length=100, verbose_name='Tipo de Veículo')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento do motorista', null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato', max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo', verbose_name='Endereço')),
                ('is_active', models.BooleanField(default=True, help_text='Motorista está ativo e pode ser designado para viagens', verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o motorista', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('transportadora', models.ForeignKey(help_text='Transportadora responsável pelo motorista', limit_choices_to={'user_type': 'TRANSPORTADORA'}, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL, verbose_name='Transportadora')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cpf'], name='drivers_dri_cpf_071c33_idx'), models.Index(fields=['cnh'], name='drivers_dri_cnh_ab2be7_idx'), models.Index(fields=['transportadora', '-created_at'], name='drivers_dri_transpo_6f8bd1_idx')],
            },
        ),
    ]
